import type { NextPage } from 'next'
import Head from 'next/head'
import Router from '@G.pages/Routes'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Curso Reactjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Router />
      </main>
    </>
  )
}

export default Home
